<a href="https://colab.research.google.com/github/JAIKUMAR264/Titanic-survival-project-using-ml/blob/main/titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
df=sns.load_dataset("titanic")

In [4]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [5]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True


In [6]:
df.shape

(891, 15)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [8]:
df.describe()

,survived,pclass,age,sibsp,parch,fare
count,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200


In [9]:
df.isnull()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
887,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False
889,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False


In [10]:
df.isnull().sum()

,0
survived,0
pclass,0
sex,0
age,177
sibsp,0
parch,0
fare,0
embarked,2
class,0
who,0


In [11]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [12]:
df.drop(['class','who','deck','embark_town','alive','adult_male'],axis=1,inplace=True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [14]:
df.isnull().sum()

,0
survived,0
pclass,0
sex,0
age,177
sibsp,0
parch,0
fare,0
embarked,2
alone,0


In [15]:
df["age"]=df["age"].replace(0,np.nan)
mdn=df["age"].median()
mdn

28.0

In [16]:
df.isnull().sum()

,0
survived,0
pclass,0
sex,0
age,177
sibsp,0
parch,0
fare,0
embarked,2
alone,0


In [17]:
df.dropna(subset=["embarked"],inplace=True)

In [18]:
df["age"].fillna(mdn,inplace=True)

In [19]:
df.isnull().sum()

,0
survived,0
pclass,0
sex,0
age,0
sibsp,0
parch,0
fare,0
embarked,0
alone,0


In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  889 non-null    int64  
 1   pclass    889 non-null    int64  
 2   sex       889 non-null    object 
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64  
 5   parch     889 non-null    int64  
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     889 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB


In [21]:
df_clean=df.copy()
df_clean=pd.get_dummies(data=df,drop_first=True)

In [22]:
from sklearn.preprocessing import LabelEncoder
Le=LabelEncoder()

In [23]:
df['sex']=Le.fit_transform(df["sex"])
df['embarked']=Le.fit_transform(df["embarked"])

In [24]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
886,0,2,1,27.0,0,0,13.00,2,True
887,1,1,0,19.0,0,0,30.00,2,True
888,0,3,0,28.0,1,2,23.45,2,False
889,1,1,1,26.0,0,0,30.00,0,True
890,0,3,1,32.0,0,0,7.75,1,True


In [25]:
df=pd.get_dummies(data=df,drop_first=True)

In [26]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,1,22.0,1,0,7.2500,2,False
1,1,1,0,38.0,1,0,71.2833,0,False
2,1,3,0,26.0,0,0,7.9250,2,True
3,1,1,0,35.0,1,0,53.1000,2,False
4,0,3,1,35.0,0,0,8.0500,2,True
...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.0,0,0,13.0000,2,True
887,1,1,0,19.0,0,0,30.0000,2,True
888,0,3,0,28.0,1,2,23.4500,2,False
889,1,1,1,26.0,0,0,30.0000,0,True


In [27]:
df=df.astype(int)
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
886,0,2,1,27,0,0,13,2,1
887,1,1,0,19,0,0,30,2,1
888,0,3,0,28,1,2,23,2,0
889,1,1,1,26,0,0,30,0,1
890,0,3,1,32,0,0,7,1,1


In [28]:
df_clean=df_clean.astype(int)
df_clean.tail()

,survived,pclass,age,sibsp,parch,fare,alone,sex_male,embarked_Q,embarked_S
886,0,2,27,0,0,13,1,1,0,1
887,1,1,19,0,0,30,1,0,0,1
888,0,3,28,1,2,23,0,0,0,1
889,1,1,26,0,0,30,1,1,0,0
890,0,3,32,0,0,7,1,1,1,0


In [29]:
df_clean.columns

Index(['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare', 'alone',
       'sex_male', 'embarked_Q', 'embarked_S'],
      dtype='object')

In [30]:
X=df.drop("survived",axis=1)
y=df['survived']

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [32]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [33]:
y_pred=model.predict(X_test)
y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [34]:
y_test

,survived
281,0
435,1
39,1
418,0
585,1
...,...
433,0
807,0
25,1
85,1


In [35]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [36]:
accuracy_score(y_test,y_pred)

0.8033707865168539

In [37]:
confusion_matrix(y_test,y_pred)

array([[90, 19],
       [16, 53]])

In [38]:
classification_report(y_test,y_pred)

'              precision    recall  f1-score   support\n\n           0       0.85      0.83      0.84       109\n           1       0.74      0.77      0.75        69\n\n    accuracy                           0.80       178\n   macro avg       0.79      0.80      0.79       178\nweighted avg       0.81      0.80      0.80       178\n'

In [39]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



In [40]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [41]:
X_train_scaled=sc.fit_transform(X_train)
X_test_scaled=sc.fit_transform(X_test)

In [42]:
#To find best k and cv scores
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
best_k=0
best_score=0
for k in range(1,22):
    knn_model=KNeighborsClassifier(n_neighbors=k)
    scores=cross_val_score(knn_model,X_train_scaled,y_train,cv=5,scoring="accuracy")
    avg_score=scores.mean()
    if avg_score>best_score:
        best_score=avg_score
        best_k=k
print("best k:",best_k)
print("average accuracy:",best_score)

best k: 4
average accuracy: 0.8269969467152565


In [43]:
from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier(n_neighbors=10)
knn_model.fit(X_train_scaled,y_train)
y_pred_knn=knn_model.predict(X_test_scaled)



In [44]:
accuracy_score(y_test,y_pred_knn)

0.8089887640449438

In [45]:
confusion_matrix(y_test,y_pred_knn)

array([[95, 14],
       [20, 49]])

In [46]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



In [47]:
from sklearn.naive_bayes import GaussianNB
nb_model = GaussianNB()
nb_model.fit(X_train_scaled,y_train)
y_pred_nb = nb_model.predict(X_test_scaled)

In [48]:
y_pred_nb

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1])

In [49]:
accuracy_score(y_test,y_pred_nb)

0.7528089887640449

In [50]:
confusion_matrix(y_test,y_pred_nb)

array([[89, 20],
       [24, 45]])

In [51]:
print(classification_report(y_test,y_pred_nb))

              precision    recall  f1-score   support

           0       0.79      0.82      0.80       109
           1       0.69      0.65      0.67        69

    accuracy                           0.75       178
   macro avg       0.74      0.73      0.74       178
weighted avg       0.75      0.75      0.75       178



In [52]:
from sklearn.naive_bayes import GaussianNB
nb1_model = GaussianNB()
nb1_model.fit(X_train,y_train)
y_pred_nb1 = nb1_model.predict(X_test)

In [53]:
y_pred_nb1

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [54]:
accuracy_score(y_test,y_pred_nb1)

0.7752808988764045

In [55]:
confusion_matrix(y_test,y_pred_nb1)

array([[84, 25],
       [15, 54]])

In [56]:
print(classification_report(y_test,y_pred_nb1))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178



In [57]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score

nb_model = GaussianNB()

cv_scores = cross_val_score(
    nb_model,
    X_train_scaled,
    y_train,
    cv=5,
    scoring="accuracy"
)

print("CV Accuracy for each fold:", cv_scores)
print("Mean CV Accuracy:", cv_scores.mean())

CV Accuracy for each fold: [0.79020979 0.79577465 0.79577465 0.81690141 0.73943662]
Mean CV Accuracy: 0.7876194228306904


In [58]:
from sklearn.metrics import accuracy_score

test_accuracy = accuracy_score(y_test, y_pred_nb)

print(test_accuracy)

0.7528089887640449


In [59]:
from sklearn.tree import DecisionTreeClassifier
dt_model=DecisionTreeClassifier()
dt_model.fit(X_train,y_train)
y_pred_dt=dt_model.predict(X_test)

In [60]:
accuracy_score(y_test,y_pred_dt)

0.7808988764044944

In [61]:
from sklearn.tree import DecisionTreeClassifier
dt_model1=DecisionTreeClassifier()
dt_model1.fit(X_train_scaled,y_train)
y_pred_dt1=dt_model1.predict(X_test_scaled)

In [62]:
accuracy_score(y_test,y_pred_dt1)

0.7247191011235955

In [63]:
from sklearn.tree import DecisionTreeClassifier
dt_model2 = DecisionTreeClassifier(
    criterion="entropy",
    random_state=42
)

In [64]:
dt_model2.fit(X_train,y_train)
y_pred_dt2=dt_model2.predict(X_test)

In [65]:
accuracy_score(y_test,y_pred_dt2)

0.7752808988764045

In [66]:
from sklearn.svm import SVC
svm_model=SVC(kernel='rbf')
svm_model.fit(X_train,y_train)
y_pred_svm=svm_model.predict(X_test)

In [67]:
y_pred_svm

array([0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [68]:
accuracy_score(y_test,y_pred_svm)

0.6853932584269663

In [69]:
from sklearn.svm import SVC
svm_model1=SVC(kernel='rbf')
svm_model1.fit(X_train_scaled,y_train)
y_pred_svm1=svm_model1.predict(X_test_scaled)

In [70]:
accuracy_score(y_test,y_pred_svm1)

0.8258426966292135

In [71]:
confusion_matrix(y_test,y_pred_svm1)

array([[96, 13],
       [18, 51]])

In [72]:
print(classification_report(y_test,y_pred_svm1))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86       109
           1       0.80      0.74      0.77        69

    accuracy                           0.83       178
   macro avg       0.82      0.81      0.81       178
weighted avg       0.82      0.83      0.82       178



In [73]:
import joblib
joblib.dump(svm_model1, 'SVM_titanic.pkl')
joblib.dump(sc, 'scaler.pkl')
joblib.dump(X.columns.tolist(), 'columns.pkl')

['columns.pkl']

In [74]:
#Training accuracy
svm_model1.fit(X_train_scaled,y_train)
y_train_pred=svm_model1.predict(X_train_scaled)
print("Training score:",accuracy_score(y_train,y_train_pred))

Training score: 0.8368495077355836


In [75]:
#cross validation
from sklearn.model_selection import cross_val_score
scores = cross_val_score(
    svm_model1,
    X_train_scaled,
    y_train,
    cv=5,
    scoring="accuracy"
)
print(scores.mean())


0.8241701960011818


In [1]:
print("Github test")

Github test
